---
name: Release
run-name: Release ${{github.ref}}
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
