---
name: Verify Release
run-name: Verify Release
on:
  workflow_run:
    workflows: ["Release Event"]
    types:
      - requested
jobs:
  verify-release:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      issues: write
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
      # Check if prerelease is changed to release
