---
name: Verify Release
run-name: Verify Release ${{github.event.workflow_run.head_branch}}
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - requested
jobs:
  verify-release:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      issues: write
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
      # Get Tag
      - id: verify
        env:
          GH_TOKEN: ${{github.token}}
          EXPECTED_EMAIL: ${{secrets.RELEASE_EMAIL}}
          TAG: ${{github.event.workflow_run.head_branch}}
        # .verification.verified
        # .tagger.email
        run: |
          sha=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --jq ".object.sha" \
            "/repos/${GITHUB_REPOSITORY}/git/ref/tags/$TAG")

          resp=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -q '"\(.verification.verified)/\(.tagger.email)"' \
            "/repos/${GITHUB_REPOSITORY}/git/tags/$sha")
          verified=${resp%/*}
          email=${resp#*/}
          echo "verified=$verified" >> "$GITHUB_OUTPUT"
          if [ "$verified" != "true" ]; then
            echo "::error:: Tag is not verified"
          fi
          if [ "$email" = "$EXPECTED_EMAIL" ]; then
            echo "email=true" >> "$GITHUB_OUTPUT"
          else
            echo "::error:: Tagger is unexpected"
            echo "email=false" >> "$GITHUB_OUTPUT"
          fi

      # Get N commits from the default branch and verify the commit SHA
      - id: commit
        env:
          GH_TOKEN: ${{github.token}}
          SHA: ${{github.event.workflow_run.head_sha}}
          LENGTH: 10
        run: |
          repo=${GITHUB_REPOSITORY#*/}
          shas=$(gh api graphql \
            -F "owner=$GITHUB_REPOSITORY_OWNER" \
            -F "repo=$repo" \
            -F "length=$LENGTH" \
            -q '.data.repository.defaultBranchRef.target.history.edges[].node.oid' \
            -f query='
              query($owner: String!, $repo: String!, $length: Int!) {
                repository(owner: $owner, name: $repo) {
                  defaultBranchRef {
                    target {
                      ... on Commit {
                        history(first: $length) {
                          edges {
                            node {
                              oid
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }')
          echo "---"
          echo "SHAS:"
          echo "$shas"
          echo "---"      
          if echo "$shas" | grep -q "$SHA"; then
            echo "default_branch=true" >> "$GITHUB_OUTPUT"
          else
            echo "::error:: The commit isn't included in the latest $LENGTH commits of the default branch"
            echo "default_branch=false" >> "$GITHUB_OUTPUT"
          fi

      - if: |
          steps.verify.outputs.verified != 'true' || steps.verify.outputs.email != 'true' || steps.commit.outputs.default_branch != 'true'
        env:
          GH_TOKEN: ${{github.token}}
          ISSUE_NUMBER: 1
          EMAIL: ${{steps.verify.outputs.email}}
          VERIFIED: ${{steps.verify.outputs.verified}}
          DEFAULT_BRANCH: ${{steps.commit.outputs.default_branch}}
          LENGTH: 10
        run: |
          tempfile=$(mktemp)
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> "$tempfile"
          if [ "$EMAIL" != true ]; then
            echo ":x: Tagger email is not expected" >> "$tempfile"
          fi
          if [ "$VERIFIED" != true ]; then
            echo ":x: Tag is not verified" >> "$tempfile"
          fi
          if [ "$DEFAULT_BRANCH" == false ]; then
            echo ":x: The commit isn't included in the latest $LENGTH commits of the default branch" >> "$tempfile"
          fi
          gh issue comment "$ISSUE_NUMBER" -R "$GITHUB_REPOSITORY" -F "$tempfile"
          rm "$tempfile"

      - if: |
          steps.verify.outputs.verified != 'true' || steps.verify.outputs.email != 'true' || steps.commit.outputs.default_branch != 'true'
        id: slack_body
        env:
          EMAIL: ${{steps.verify.outputs.email}}
          VERIFIED: ${{steps.verify.outputs.verified}}
          DEFAULT_BRANCH: ${{steps.commit.outputs.default_branch}}
          LENGTH: 10
        run: |
          tempfile=$(mktemp)
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> "$tempfile"
          if [ "$EMAIL" != true ]; then
            echo ":x: Tagger email is not expected" >> "$tempfile"
          fi
          if [ "$VERIFIED" != true ]; then
            echo ":x: Tag is not verified" >> "$tempfile"
          fi
          if [ "$DEFAULT_BRANCH" == false ]; then
            echo ":x: The commit isn't included in the latest $LENGTH commits of the default branch" >> "$tempfile"
          fi
          {
            echo 'text<<EOF'
            cat "$tempfile"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT" 
          rm "$tempfile"

      - if: |
          steps.verify.outputs.verified != 'true' || steps.verify.outputs.email != 'true' || steps.commit.outputs.default_branch != 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ toJson(steps.slack_body.outputs) }}

      - if: |
          steps.verify.outputs.verified != 'true' || steps.verify.outputs.email != 'true' || steps.commit.outputs.default_branch != 'true'
        run: |
          echo "::error:: The validation failed"
          exit 1
