---
name: Verify Tag
run-name: Verify Tag ${{github.event.workflow_run.head_branch}}
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - requested
jobs:
  verify-release:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      issues: write
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
      - uses: suzuki-shunsuke/verify-tag-action@main
        id: verify
        with:
          tag: ${{github.event.workflow_run.head_branch}}
          commit_sha: ${{github.event.workflow_run.head_sha}}
          slack_incoming_webhook_url: ${{secrets.SLACK_INCOMING_WEBHOOK_URL}}
          tagger_emails: ${{secrets.RELEASE_EMAIL}}
          issue_number: "1"
      - run: echo ":"
        env:
          EMAIL: ${{steps.verify.outputs.tagger_email}}
          VERIFIED_TAG: ${{steps.verify.outputs.verified_tag}}
          COMMIT: ${{steps.verify.outputs.commit_in_default_branch}}
